server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Users/joyeseul/Spring/native-file-repo
#        git:
#          uri: https://github.com/SPRING-STUDY-2023/yeseul-spring-cloud-msa-config