server:
  port: 8761 # ??? ??? ? ??? ???? ???? ??? ?? ?? ?? ??

spring:
  application:
    name: discoveryservice # ???????? ??? id ??
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: ecommerce

eureka:
  client: # ???? ??? ? ??? false ??
    register-with-eureka: false # default ? ture
    fetch-registry: false