server:
  port: 8080 # ??? ??? ? ??? ???? ???? ??? ?? ?? ?? ??

spring:
  application:
    name: discoveryservice # ???????? ??? id ??

eureka:
  client: # ???? ??? ? ??? false ??
    register-with-eureka: false # default ? ture
    fetch-registry: false